// <auto-generated />
using Ecommerce;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610131447_AddQuantityColIntoProduct")]
    partial class AddQuantityColIntoProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobiles"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptops"
                        });
                });

            modelBuilder.Entity("Ecommerce.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest iPhone model",
                            Name = "iPhone 13",
                            Price = 999.99m,
                            Quantity = 0,
                            Rate = 4.5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Flagship Samsung phone",
                            Name = "Samsung Galaxy S21",
                            Price = 899.99m,
                            Quantity = 0,
                            Rate = 4.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Powerful tablet from Apple",
                            Name = "iPad Pro",
                            Price = 799.99m,
                            Quantity = 0,
                            Rate = 4.5999999999999996
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Versatile tablet from Microsoft",
                            Name = "Microsoft Surface Pro",
                            Price = 899.99m,
                            Quantity = 0,
                            Rate = 4.4000000000000004
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "High-performance laptop from Apple",
                            Name = "MacBook Pro",
                            Price = 1299.99m,
                            Quantity = 0,
                            Rate = 4.7000000000000002
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Compact and powerful laptop from Dell",
                            Name = "Dell XPS 13",
                            Price = 999.99m,
                            Quantity = 0,
                            Rate = 4.5
                        });
                });

            modelBuilder.Entity("Ecommerce.Product", b =>
                {
                    b.HasOne("Ecommerce.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
